### ISSUE TITLE
battery charge voltage limit became 4192mV

### ISSUE THREAD

**Issue by hukaka22** [suchmememanyskill/TegraExplorer#100]
After I launch script system wipe in TegraExplorer on Switch Lite, the battery charge voltage limit became 4192mV,  before script system wipe is 4320mV.
How can I solved it? Thanks!

**Comment by suchmememanyskill** [comment]
See the latest pre-release.
You can restore the original values by restoring a nand/emmc backup

**Comment by hukaka22** [comment]
I already see the latest pre-release,and it says "If you have previously ran the systemwipe script on a lite, you cannot run this script again to fix this".So how can I fix it? I don't have nand/emmc backup.

**Comment by impeeza** [comment]
you can not,  that's why you need to RTM.

you can try https://gbatemp.net/threads/fix-for-linux-battery-issue.508715/  but I don't think you can fix the error, please search for further help on discord or GBAtemp.

**Comment by suchmememanyskill** [comment]
> I don't have nand/emmc backup.

Then for the future, this is why backups are important.

You're probably never getting those original values back, then. You might get close by copying the aging save of someone else but this also is completely nonsensical to do.
