### ISSUE TITLE
SystemWipe Error on OLED Switch

### ISSUE THREAD

**Issue by archit9169** [suchmememanyskill/TegraExplorer#101]
I am getting an error -> save dir deletion failed

I am on the latest firmware and prodkeys were dumped succesfully. On getting the error, the script does not show done and no further text are desiplayed. When rebooting, the system shows the setup screen for new console.

Any ideas whats going on? I have a rawnand backup and noticed no further issue so have not restored the backup yet.

I am new to all this modding so let me know if I need to understand something that I might not be familiar with.

**Comment by suchmememanyskill** [comment]
Why are you performing a systemwipe? It sounds like your USER partition is not entirely intact, may be worth checking how the user partition looks (explore emmc > USER)

**Comment by archit9169** [comment]
> Why are you performing a systemwipe? It sounds like your USER partition is not entirely intact, may be worth checking how the user partition looks (explore emmc > USER)

I had a dirty system and wanted to wipe everything.

For now its working fine and I am not sure exactly what to check in user folder. But it is mostly empty, only system folder has some firmware update files in save directory.

**Comment by archit9169** [comment]
Tried opening it in NxNandManager, and can only see that Backup GPT is gone now after system wipe using this payload. My old nand dump still has that, so if needed I can do a restore.

User dir has the standard 3 empty folders, only system dir has any files in contents and save folders.
user/temp
user/Album
user/Contents/Registered
user/Contents/placehld
and a single file in user dir called PRF2SAFE.RCV of 14KB

**Comment by suchmememanyskill** [comment]
TegraExplorer doesn't nuke the backup gpt, that's very odd.

Also, those 4 folders are most certainly not the 'default'. I expect the following to exist:

- Album
- Contents/placehld
- Contents/registered
- save
- saveMeta
- temp

**Comment by archit9169** [comment]
> TegraExplorer doesn't nuke the backup gpt, that's very odd.
> 
> Also, those 4 folders are most certainly not the 'default'. I expect the following to exist:
> 
> * Album
> * Contents/placehld
> * Contents/registered
> * save
> * saveMeta
> * temp

Dont think that the user folder is the cause. Its most probably refering to the save folder inside system.

Edit: there is no save folder in user for me, all that is empty anyway. Is there any check in the script to see if folder exist before trying to delete?

**Comment by suchmememanyskill** [comment]
Just saying that those folders not existing, to my knowledge, is not normal. It does cause the script to fail. Probably should safeguard against that but still odd.

The wipe is also the last thing it does, so if that fails but the folders in user are empty it's done its job, just be aware that such situations may be the result of something more serious (corruption, hardware failure)

**Comment by archit9169** [comment]
> Just saying that those folders not existing, to my knowledge, is not normal. It does cause the script to fail. Probably should safeguard against that but still odd.

I think these folders were not created as I already did a system wipe using switch settings. I checked and saw several save files in system that should not have been present for a perfect wipe, so tried this script.

Yes, if there is no safeguard then it would fail and give that error. 

Can you also give a brief of what this script erases? Not sure why people were mentioning battery and other issues due to this script. Does this also erase any other folders aside from system and user?

**Comment by suchmememanyskill** [comment]
It erases all system saves and all user data. One of the system saves manages battery calibration (switch's power management is purely done in software).

The latest version of TE resolves this by not deleting the save associated with battery management

**Comment by archit9169** [comment]
> It erases all system saves and all user data. One of the system saves manages battery calibration (switch's power management is purely done in software).
> 
> The latest version of TE resolves this by not deleting the save associated with battery management

Which save is that? On a brand new system or one created from scrach aside from firmware nca files there should only be 2 save files right? One is for index and the other one is for this or something?

Bear with me, got my switch just 2 days ago, so learning stuff as I go. Have a rawnand backup so not afraid to mess things up.

**Comment by archit9169** [comment]
Backup GPT is also not deleted, the software was just not displaying it properly. I am going to close the issue now that we have found the cause for the failure, or should I keep it open until fix is merged?

**Comment by suchmememanyskill** [comment]
> Which save is that? On a brand new system or one created from scrach aside from firmware nca files there should only be 2 save files right? One is for index and the other one is for this or something?

DeviceSettings, 8000000000000053

> there should only be 2 save files right?

Unsure what N ships their consoles with tbh. It does likely have some saves populated for calibration.

> One is for index and the other one is for this or something?

The 2 critical ones are 8000000000000120 (installed system nca/sysmodule index) and 8000000000000000 (system save index)

**Comment by archit9169** [comment]
> DeviceSettings, 8000000000000053

Pretty sure I deleted that manually, then used emmchaccgen to resotre system files for complete wipe.
Seems to have been recreated and no issues. Is this something that only affects lite, mine is oled?

**Comment by suchmememanyskill** [comment]
No, all consoles are affected (battery will be miscalibrated). But with other models, the default values are safe. With the lite the battery will be overcharged

**Comment by archit9169** [comment]
> No, all consoles are affected (battery will be miscalibrated). But with other models, the default values are safe. With the lite the battery will be overcharged

Seems a bit different from my case. I am still running emuMMC from original files, and sysMMC with the restored files after deleting everything. Switching between them, I do not see any calibration issues. They both have sepearet files in their system save dir.

**Comment by archit9169** [comment]
I am closing this as there is no point keeping it open. If you need this to track any pr for fix or something then please reopen.
