### ISSUE TITLE
KeyDump Fail on Oled

### ISSUE THREAD

**Issue by Vampitech** [suchmememanyskill/TegraExplorer#102]
I'm trying to run a script to do some cleaning and update stuff on the SD with #REQUIRE KEYS header but in OLED i got this screen.
![image](https://github.com/user-attachments/assets/8b2b6edb-1845-4201-9294-9eb74b012867)

Dump keys from Lockpick_RCM doesn't help at all. Any ideas?

Thanks in advance

**Comment by impeeza** [comment]
Hi, can you share the script please?

**Comment by Vampitech** [comment]
> Hi, can you share the script please?

Sure,


`#REQUIRE SD
#REQUIRE MINERVA

copydir("sd:/upd/atmosphere", "sd:/")
copydir("sd:/upd/bootloader", "sd:/")
copydir("sd:/upd/config", "sd:/")
copydir("sd:/upd/NEXT", "sd:/")
copydir("sd:/upd/switch", "sd:/")
copyfile("sd:/upd/boot.ini", "sd:/boot.ini")
copyfile("sd:/upd/boot.dat", "sd:/boot.dat")
copyfile("sd:/upd/hbmenu.nro", "sd:/hbmenu.nro")
copyfile("sd:/upd/exosphere.ini", "sd:/exosphere.ini")
copyfile("sd:/upd/payload.bin", "sd:/payload.bin")
deldir("sd:/NEXT")


wait(tw = 5000)
payload("sd:/payload.bin")
exit()
`

**Comment by Vampitech** [comment]
> Hi, can you share the script please?

Sure,

```
#REQUIRE SD
#REQUIRE MINERVA

copydir("sd:/upd/atmosphere", "sd:/")
copydir("sd:/upd/bootloader", "sd:/")
copydir("sd:/upd/config", "sd:/")
copydir("sd:/upd/switch", "sd:/")
copyfile("sd:/upd/boot.ini", "sd:/boot.ini")
copyfile("sd:/upd/boot.dat", "sd:/boot.dat")
copyfile("sd:/upd/hbmenu.nro", "sd:/hbmenu.nro")
copyfile("sd:/upd/exosphere.ini", "sd:/exosphere.ini")
copyfile("sd:/upd/payload.bin", "sd:/payload.bin")
deldir("sd:/upd")

payload("sd:/payload.bin")
exit()
```

**Comment by suchmememanyskill** [comment]
Not interested in supporting aio's here, especially a bad one at that

**Comment by Vampitech** [comment]
> Not interested in supporting aio's here, especially a bad one at that

Whoa! Despite giving you all the credit and supporting your work, you come out with this. You have every right. But it still speaks very badly of you as a person. But that's okay.I will find a way to fix it on my own, luckily I have the knowledge to do it. And in fact the issue does not only affect an AIO, it also affects any user with an OLED that wants to use TegraExplorer and that means that you're are a bad developer. I think that sucks more than my "Bad AIO"

Thanks for nothing.
