### ISSUE TITLE
error keydump failed

### ISSUE THREAD

**Issue by hayder9445** [suchmememanyskill/TegraExplorer#103]
I have an OLED switch updated to 19.0.1 and I'm getting this error.
![WhatsApp Image 2024-11-18 at 18 18 01_58d48e54](https://github.com/user-attachments/assets/10352be4-7a49-4ff3-b067-c44be32d534c)

**Comment by suchmememanyskill** [comment]
Either the sd is not mounted/inserted or sd:/switch/prod.keys doesn't exist (use lockpick_rcm to dump keys).

I don't support dumping keys without prod.keys on oled
