### ISSUE TITLE
I get an error after injecting dump_biskey error code 57

### ISSUE THREAD

**Issue by bonjorys** [suchmememanyskill/TegraExplorer#15]
I can continue after the error message, I'm just not sure if it's going to work if I continue and try and set things up? 
![IMG_20200417_154237](https://user-images.githubusercontent.com/63859794/79908098-91494f80-8412-11ea-8c5a-0940511d48f1.jpg)

**Comment by bonjorys** [comment]
Sorry looks like you have an update out anyway, will give that a try

**Comment by suchmememanyskill** [comment]
You're not running the latest version here. Did the latest version fix it?

**Comment by suchmememanyskill** [comment]
Feel free to re-open if this happens on the latest version
