### ISSUE TITLE
When formatting for EmuMMC, I get error 14.

### ISSUE THREAD

**Issue by TealingYT** [suchmememanyskill/TegraExplorer#2]
Hello, whenever I try to format my SD Card with the EmuMMC part of TegraExplorer, it gives me the error "f_mkfs returned 14!". It formats to FAT32 perfectly, however.

**Comment by suchmememanyskill** [comment]
No idea why that would happen. Can you give some more info in my discord and ping me? (https://discord.gg/nsZVS2)

**Comment by suchmememanyskill** [comment]
After some testing by @el-emmo , it seems that sd cards that are 32gb in size error out with f_mkfs 14 on TegraExplorer 1.0.1. How big is your sd card?

**Comment by TealingYT** [comment]
Hello, I have a 32gb SD card, however, I used the version before the latest and that did the trick.

**Comment by suchmememanyskill** [comment]
yes, but TegraExplorer 1.0.0 formats with a 8k cluster size, which is very slow. I'd suggest not using an emummc on a 32gb sd card

**Comment by DEATH117** [comment]
so you recommend not using a 32g or you cant at all?

**Comment by suchmememanyskill** [comment]
`I'd suggest not using an emummc on a 32gb sd card` i already gave an answer to this
