### ISSUE TITLE
v2.0.0 Controls UnResponsive

### ISSUE THREAD

**Issue by ekoandrew** [suchmememanyskill/TegraExplorer#20]
awesome to see new release, got it installed via HB App Store, loaded over to Bootloader>Payload folder. Boot it up from Hek menu. Sadly, first impression looks good, lastly it ended terrible...can not shut down properly due to Navigation Keys are Not Working. Joy Con dont work. detach Joy Con, traditional Vol + - / Pwr don't work either.

Switch: 10.0.2 / Kosmos 16

**Comment by suchmememanyskill** [comment]
Interesting, if you disconnect your joycons, do you see `JOYL JOYR MISS` in the bottom right? (is the application not frozen?), is this repeatable?

**Comment by ekoandrew** [comment]
Detached Joy Con works.

But with JoyCon it have issues to stay put...

**Comment by ekoandrew** [comment]
Sorry, forgot. Yes this is Repeatable for any Joy Con I put onto Switch.
It keeps bouncing back from Exit... or stuck on first Line.

**Comment by suchmememanyskill** [comment]
try to push your stick in while it's dead centre (this will reset it's position to that), did that as controllers get calibrated at boot, if you mess with the sticks then it will mess it up, pressing the sticks in re-calibrates them

**Comment by ekoandrew** [comment]
Thank You! Your response has made it worked Perfectly!!!

Maybe you should add an FAQ: “What If Troubleshoot”.

Thanks Again
