### ISSUE TITLE
Bug with function fs_openDir() and fs_readDir()

### ISSUE THREAD

**Issue by shadow2560** [suchmememanyskill/TegraExplorer#22]
Hi,

I think I have found a problem with the functions mensioned in the issue title that impact the setStringIndex() function. 

To reproduce it, take the script joined, copy it on your SD, use an SD with 5 or six folders on it to realy see the effect of the bug, execute the script and move into the menu displayed.

I think there is more problem with this script because what will be the display with an SD with 100 folders on it (sliding of the screen will not work I think but not realy the point here).

A little thing that could be added with "fs_openDir()" vars created with this function could be a "$PARENTDIR" string var that give you the parent folder, I haven't found a technic to do that with the actuals functions.

[bugged_scripttest.zip](https://github.com/suchmememanyskill/TegraExplorer/files/4738160/bugged_scripttest.zip)

**Comment by suchmememanyskill** [comment]
Not an issue. Your script was incrementing maxSelection in the fs section while your previous menu printer depended on it being 5. See here for a fix
[fixed_scripttest.zip](https://github.com/suchmememanyskill/TegraExplorer/files/4738780/fixed_scripttest.zip)

Note that if setStringIndex() does not find a string at the specified index it will error out. This is what was causing the issue

**Comment by shadow2560** [comment]
So stupid I am... sory and thanks.

**Comment by shadow2560** [comment]
Just for information, with your help on this problem I've managed to do [this script](https://github.com/shadow2560/Ultimate-Switch-Hack-Script/blob/master/languages/EN_us/tegra_scripts/cdj_restore_firmware.te), probably far from perfect (especialy on refreshing the folder explorer but I haven't found an other solution for that) but at least work on most case.
