### ISSUE TITLE
Request : dump .ncmt.nca for firmware update with daybreak

### ISSUE THREAD

**Issue by deejay87** [suchmememanyskill/TegraExplorer#24]
Hi
Can you update to dump the firmware and have the good files  .ncmt.nca for update with daybreak who is coming ?
Thanks

**Comment by suchmememanyskill** [comment]
This will be pretty hard to implement, considering i have to dump keys and read into the nca header, both of which i don't have implemented. I'll think about it

**Comment by deejay87** [comment]
ok thanks, new for me, i'm looking how to do this for testing :)

**Comment by suchmememanyskill** [comment]
Implemented in commit b42b52e in the dev branch
