### ISSUE TITLE
Problem when dump firmware for daybreak: TegraExplorer 2.0.4

### ISSUE THREAD

**Issue by leandrodeassis** [suchmememanyskill/TegraExplorer#25]
![Screenshot_1f158645](https://user-images.githubusercontent.com/889104/89217142-0bf14180-d5a2-11ea-8c24-254314766ddf.png)

prod.keys in sd:/switch/ folder.
hekate 5.3.2 on sd.
SysNAND with Firmware 10.1.0
EmuNAND Hidden Partition with Firmware 10.1.0

**Comment by leandrodeassis** [comment]
ok, worked when I enter to EMMC first.

**Comment by suchmememanyskill** [comment]
too little information given. I cannot reproduce this.
