### ISSUE TITLE
Switch stays blank after injecting the payload

### ISSUE THREAD

**Issue by dfear** [suchmememanyskill/TegraExplorer#27]
I have injected the payload using TegraRcmGui and the screen stays blank.

I have tried versions 2.0.4 and 2.0.3, also I have tried both 2.0.3 and 2.0.4 with the SD card inserted.

The SD card is formatted with exfat and has (just) the bootloader folder of Hekate on it. I am using: hekate - CTCaer mod v5.3.0 & Nyx v0.9.2.

I did have 2.0,4 working once, but it didn't have the options to either format the SD card or dump the firmware.

**Comment by suchmememanyskill** [comment]
Hi, does this also happen without your sd inserted? also, did you power cycle after each attempt? does the backlight of the screen turn on?

**Comment by dfear** [comment]
1) Yes it happens without the SD card inserted. 
2) what's the recommended way to power cycle the switch?
3) not sure, will try again and observe.

**Comment by suchmememanyskill** [comment]
for 2: hold power for 15 seconds then enter rcm again. Also, can you join my discord? probably better to help via that. Also hm

**Comment by dfear** [comment]
i'm on your discord now (as: dfear).

**Comment by dfear** [comment]
> Hi, does this also happen without your sd inserted? also, did you power cycle after each attempt? does the backlight of the screen turn on?

The backlight doesn't turn on.

**Comment by carlosen14** [comment]
any solution on this?
