### ISSUE TITLE
Make support on Mariko consoles

### ISSUE THREAD

**Issue by zal16** [suchmememanyskill/TegraExplorer#29]
I tried to run on Mariko console,, but i get a blackscreen after chainloading under hekate

**Comment by suchmememanyskill** [comment]
Tegraexplorer is currently not updated to run under patched erista and mariko consoles. I will get on that when time allows for that

**Comment by suchmememanyskill** [comment]
hi, question, could you test this again with the 3.0.0 beta? i've never tested it but it should work now

**Comment by zal16** [comment]
Yeah! This works.
Copy, Paste, EMMC browsing, scripts, all works.

**Comment by suchmememanyskill** [comment]
Oh cool! Good to know, thanks

**Comment by suchmememanyskill** [comment]
i've released 3.0.0 now, so this issue can now be closed i suppose
