### ISSUE TITLE
 I get an error after injecting dump_biskey error code 57

### ISSUE THREAD

**Issue by Mafaveli** [suchmememanyskill/TegraExplorer#30]
I'm not sure what I have done wrong,
SysNAND 11.0.1
EmuMMC 10.2.0
Hekate 5.5.1
Atms 16.1

Wanted to dump my sysNAND to update emuMMC using day break, I have managed to successfully download my Prodkeys with lock pick. 

Your help would be much appreciated. Thanks

**Comment by suchmememanyskill** [comment]
Are you injecting tegraexplorer v2.0.5? Check the top left of the screen as well. Only v2.0.5 supports 11.0.x+

**Comment by Mafaveli** [comment]
OK will give that a shot, I did use the latest release on github so I assumed it would be compatible, but yes it seems you're probably right, not sure why it gave me 2.0.4 as I only downloaded from guy hub this morning. Thanks for getting back to me, will check it out and update on here.
