### ISSUE TITLE
Help with arrays with scripts on TegraExplorer V3

### ISSUE THREAD

**Issue by shadow2560** [suchmememanyskill/TegraExplorer#33]
I want to create an empty array and add values in it one by one but I don't know how to do this. Here is a code example to ilustrate what I want to do (I know that adding a value in an array doesn't work like that but I think that my example is more understandable like that):

```
file = dirRead(CWD)
folder_list = []
i = 0
j = 0
while (i < len(file)) {
	if (fileProperties[i]) {
		folder_list[j] = file[i]
		j = j + 1
	}
	i = i + 1
}
```

Thanks in advance for the help.

**Comment by suchmememanyskill** [comment]
There are 2 issues with this:
1. Currently you cannot expand a string array, making what you want to do impossible
2. Currently you cannot make an empty array as it needs to have a type associated with it

I'll see if i can adress these in the next update

**Comment by shadow2560** [comment]
OK that's what I had understoud from the doc of TegraScript but I have prefered to ask it to you. I will do what I want to do with an other method and I will keep an eye on your futur updates.

Thanks for the quick answer.

**Comment by suchmememanyskill** [comment]
Just pushed a commit to TegraExplorer's master branch (see the actions tab to get the build of that commit). Your example is now possible as follows:

```
files = dirRead(_CWD)
folder_list = []
i = 0
while (i < len(files)){
    if (fileProperties[i]){
        folder_list = folder_list + files[i]
    }
    i = i + 1
}
```

**Comment by shadow2560** [comment]
I have compiled it and it work, thanks for the quick implementation, I close this issue.

An other thing cause me trouble, this code goes to infinite loop and I think it shouldn't (the "println", pause() and "color" are only there to help you to debug more easily):

```
max = 12
i = 0
while (i < max) {
	pause()
	color("WHITE")
	println(i)
	color("GREEN")
	a = (i + 1 <= max)
	println(a)
	if (i + 1 <= max) {
		color("RED")
		i = i + 1
		println(i)
	}
}
```

If you prefer I can open an other issue for this, don't hesitate to tell me. For info, a command like "if (i + 1 == max)" work, I think there is an issue with some operators like "<=" and maybe some others but the "<=" and the "==" are the only one that I have tested with a math operation on the left side (on the right side the math operations doesn't seem to work but maybe this point is normal).

**Comment by suchmememanyskill** [comment]
even though there seem to be issues with <= (maybe >=), this is quite a terrible way to make a for loop. anyway, i'll look into this

**Comment by suchmememanyskill** [comment]
oh actually, i found the issue already, this broke when i implemented bitshifting.

**Comment by suchmememanyskill** [comment]
pushed a commit to fix it. Do note to make a for loop like you want to make you'd just

```
i = 0
max = 12
while (i < max){
    println(i)
    i = i + 1
}

**Comment by shadow2560** [comment]
This was just a very simplified example to ilustrate a problem that I have identified during my unbrick script remake for TegraExplorer V3, I have coded this example to show a bug in the script function, I knew that the "if" is unusful here cause the condition is already in the while. Again, thanks for your quick support.

I don't see your new commit to fix this bug, is it normal?

**Comment by suchmememanyskill** [comment]
oh! lol i didn't push my commit, oops

**Comment by shadow2560** [comment]
I understand, I've tried the new version and it is fixed.

I rewrite [my old script](https://github.com/shadow2560/Ultimate-Switch-Hack-Script/blob/master/languages/EN_us/tegra_scripts/cdj_restore_firmware.te) that I used before, for now with my rewrite that I haven't published yet only the part with the custom folder selection doesn't work but the others things are rewritten and work.
