### ISSUE TITLE
Support other controller?

### ISSUE THREAD

**Issue by lowburger** [suchmememanyskill/TegraExplorer#34]
Hi. It's possible support other controller like hori on TegraExplorer? Here we see the support on hekate: https://github.com/CTCaer/hekate/commit/1a797bf93a6fc4ba8e645458050707fe76f0980a

**Comment by suchmememanyskill** [comment]
I updated the bdk (from hekate v5.5.2) right after releasing TE 3.0.1, try the latest github actions build

**Comment by lowburger** [comment]
Thanks I just see this checking on new commits, next time I check before issue :sweat_smile:
