### ISSUE TITLE
How ByteArray work

### ISSUE THREAD

**Issue by shadow2560** [suchmememanyskill/TegraExplorer#36]
I don't understand how ByteArray work, I think I need a small example. For example if I want to write "AbCd" in a file "test.txt" in the root of my SD, how should I use the fileWrite() function (this could be an example to integrate in the readme of TegraScript project)?

Thanks.

**Comment by suchmememanyskill** [comment]
you cannot easily write text to a file. the byte array is written litteraly to the file, so a 0x0 in a byte array will mean a 0 byte will be written to a file.

**Comment by shadow2560** [comment]
That's what I have understand but I need to do something like that.

But for my example I've tried this:
`fileWrite("sd:/test.txt", [0x41, 0x62, 0x43, 0x64])`

It doesn't work so how should I declare this, I need to have a correct example to understand.

**Comment by suchmememanyskill** [comment]
fileWrite takes a byte array, so `fileWrite("sd:/test.txt", byte([0x41, 0x62, 0x43, 0x64]))` will work

**Comment by shadow2560** [comment]
OK thanks, this work perfectly like that.
