### ISSUE TITLE
blanck screen

### ISSUE THREAD

**Issue by carlosen14** [suchmememanyskill/TegraExplorer#37]
When I inject it, it just stays a blank screen. 

this is the output

yes, is connected on an USB 3 (blue)

```sh
carlos@carlos-zbook:~/Desktop/respaldo/fusee-interfacee-tk-linux$ sudo ./PayloadInjector 
[sudo] password for carlos: 

Important note: on desktop Linux systems, we currently require an XHCI host controller.
A good way to ensure you're likely using an XHCI backend is to plug your
device into a blue 'USB 3' port.

Identified a Linux system; setting up the appropriate backend.
Found a Tegra with Device ID: b' _SOME HEX CODES_ '

Setting ourselves up to smash the stack...
Uploading payload...
Smashing the stack...
skipping checks
The USB device stopped responding-- sure smells like we've smashed its stack. :)
Launch complete!
```
tried with v3.0.4 and 3.0.2.
injected using [linux payload injector v1.0.1](https://github.com/nh-server/fusee-interfacee-tk/releases)  also tried with android REKADO app.

any help?

**Comment by suchmememanyskill** [comment]
Can you inject other payloads (Like fusee-primary, hekate, lockpick_rcm)? Is your switch unpatched?

**Comment by carlosen14** [comment]
yes, i can inject others, my switch has CFW since 1 year

**Comment by suchmememanyskill** [comment]
Can you attempt to chainload TE via hekate by putting it into sd:/bootloader/payloads and launching it via hekate's payload section? Can you attempt injection with your sd ejected? Does version 2.x work?

**Comment by carlosen14** [comment]
Does version 2.x work? YES, it booted

do the script launch works the same as on v3.x.x?

**Comment by suchmememanyskill** [comment]
It does not (also check discord, i think i just pinged you in nintendo homebrew)

**Comment by suchmememanyskill** [comment]
(Issue is sd card related)

**Comment by carlosen14** [comment]
solved injecting payload without SD Card inserted :+1:
