### ISSUE TITLE
Error 16

### ISSUE THREAD

**Issue by mrmikey05** [suchmememanyskill/TegraExplorer#38]
Hi there,
Something is wrong my switch lately and I can't boot it anymore. I tried to wipe my switch using the systemwipe.te and TegraExplorer.bin. I get an error, 
err: 16 
line: 223 
file: source/main.c
desc: E Reset.

What is going on?

**Comment by suchmememanyskill** [comment]
Likely hardware failure. What happens if you deleted every save in emmc > system > save except that end in 0120, 00d1 and 0047? Also where does the script and what i said above fail?

**Comment by suchmememanyskill** [comment]
(Closing this)
