### ISSUE TITLE
Can't add SD prep files after formatting via TegraExplorer

### ISSUE THREAD

**Issue by gdavidson0418** [suchmememanyskill/TegraExplorer#4]
After formatting 64gb SD with TegraExplorer payload, no open partition to add files to. There's the 16gb unallocated, 30.3gb (other), and 29.2gb (unformatted). Should I format the unformatted partition to FAT32 to add the CFW files or the other partition?

**Comment by suchmememanyskill** [comment]
This doesn't look like an actual issue, more like support. See https://github.com/suchmememanyskill/TegraExplorer#support for where to get support (Hint, it's not the issues tab here)
