### ISSUE TITLE
ERROR NO FAT

### ISSUE THREAD

**Issue by tiagofcp** [suchmememanyskill/TegraExplorer#45]
When I try to use tegraexplorer to run systemwipe I get error saying can’t mount system because of no fat
![image](https://user-images.githubusercontent.com/12100048/127779385-4e216c36-09d8-4d85-9edc-fd5304ab35b5.jpg)

I have a mariko console. Do I need to flash the chip with spacecraft?

**Comment by suchmememanyskill** [comment]
did it give a message about being unable to dump the keys when you booted tegraexplorer? You need keys to decrypt SYSTEM

**Comment by tiagofcp** [comment]
![Uploading 05930CD6-FA48-4187-81D1-4181BB297082.jpeg…]()


It’s says grabbing prod.keys… done. Like the image above 
 And then I need to click some button and it goes to the next screen

**Comment by suchmememanyskill** [comment]
Can you go into explore emmc and try to enter any of the folders?

Also, why are you even attempting a systemwipe

**Comment by tiagofcp** [comment]
Trying to open the system folder, safe or user for the same error

I bought a used switch, and it had the CFW on sysnand, and the guy does not have a clean nand backup, I want to have the sysnand to play original games online, the console was never online. 

I tried to run haku33 to clean the nand but got the same issue, and the guy told me to test with systemwipe

**Comment by suchmememanyskill** [comment]
Does the console boot normally. Did you dump the keys using lockpick_rcm on this console

**Comment by tiagofcp** [comment]
Yes boots fine. Already have atmosphere running on emunand. Lockpick works. But I think not 100% check this picture 
![image](https://user-images.githubusercontent.com/12100048/127783511-1dd6f3ce-1b71-4ccd-98b2-114fbc81dc20.jpg)

**Comment by suchmememanyskill** [comment]
What bis keys does TegraExplorer report you having in show keys? Is it all 0's or is it a mess of letters and characters

**Comment by tiagofcp** [comment]
It’s all 0
 
I know. But for tegra explorer it’s also required spacecraft?

I waiting on a set of keys to open the switch and flash the chip

**Comment by suchmememanyskill** [comment]
TegraExplorer pulls keys from prod.keys. If they are invalid, then no wonder the keys TegraExplorer has are also invalid. Dump the keys properly using lockpick_rcm

**Comment by tiagofcp** [comment]
@suchmememanyskill but lockpick can extract the prod.keys and partiales.keys. i think they are all good all have renadom letters and numbers.

**Comment by tiagofcp** [comment]
@suchmememanyskill  already flashed my chip with spacecraft, its the same as before, lockpick can extrat the file prod.keys, and they are fine but inside tegraexplorer if i go to view dumped keys its all 0000

**Comment by suchmememanyskill** [comment]
can you open your prod.keys in notepad(++) and verify your BIS_KEY's are not just 0's?

**Comment by tiagofcp** [comment]
@suchmememanyskill its the same thing with version4, yes the prod.keys opens and they are not 0's.

But i think its strange, i was checking lockpick_rcm github issues, there a guy that posted a prod.keys file there only one key changes from mine that the device_key_4x. shouldm't the bis_key be uniques? i think something is wrong with lockpick_rcm

**Comment by suchmememanyskill** [comment]
Bis keys are unique per console yes

Hm, the forced prod.keys load works for me (holding vol- during boot), and i don't have a mariko unit to test. Could you join my discord linked in the readme and ping me?

**Comment by tiagofcp** [comment]
sure 
joined already

**Comment by kriemhild3ds** [comment]
where can I find the server link? having the same issue..

**Comment by impeeza** [comment]
![image](https://github.com/suchmememanyskill/TegraExplorer/assets/41979604/24b81ed7-30bb-4037-a91b-7afeda6d8a23)

**Comment by Letmeload** [comment]
I got exact the same error. Has the problem been solved?

**Comment by suchmememanyskill** [comment]
@Letmeload this error means your internal storage couldn't be read properly. Either invalid biskeys, corrupt storage, inconsistent reads, etc. There is no specific 'fix'. There is something abnormal about your setup
