### ISSUE TITLE
Add two slash (//) to disable code

### ISSUE THREAD

**Issue by carcaschoi** [suchmememanyskill/TegraExplorer#49]
For example:

println("Hello world!")
//println("Testing")           <-Disable this line
println("I am handsome")    <-continue with this line

**Comment by bleck9999** [comment]
You can already do this by using a `#` instead of `//`

**Comment by suchmememanyskill** [comment]
Yeah, in tegrascript a comment is `#`, everything after the comment is ignored until the next line
