### ISSUE TITLE
Broken error text output

### ISSUE THREAD

**Issue by Yoti** [suchmememanyskill/TegraExplorer#51]
Variable and some text before it in [this line](https://github.com/suchmememanyskill/TegraExplorer/blob/master/source/keys/keys.c#L246) are printed as `'KG1: '20210805123730` (instead of single quote is forward apostrophe).

**Comment by suchmememanyskill** [comment]
I've already noticed this. I think something is going very wrong somewhere

**Comment by suchmememanyskill** [comment]
Fixed in latest commit. I was printing 1 character too many and the last character happened to be a CR
