### ISSUE TITLE
Nothing shows on tegraexplorer.

### ISSUE THREAD

**Issue by BgomezSuperpapotas** [suchmememanyskill/TegraExplorer#59]
Im trying to unbrick my switch, but i cant. Tegraexplorer wont show anything. I just have a white screen As shown on image.
![WhatsApp Image 2021-12-10 at 2 35 57 PM](https://user-images.githubusercontent.com/92190797/145638071-d36379f5-b595-4288-bdd4-a54499f94642.jpeg)
.

**Comment by suchmememanyskill** [comment]
After doing what? Steps to reproduce maybe?

**Comment by BgomezSuperpapotas** [comment]
Its a fresh hekate/atmos install. Fresh SD fat32/also happens with exFAT, i think my nand is damaged, i have no idea. It always happens when i launch tegraexplorer from hekate, or tegrarcmgui

**Comment by suchmememanyskill** [comment]
It tries to derive keys on boot so this with a broken emmc will likely not work properly. Try holding volume - while booting

**Comment by BgomezSuperpapotas** [comment]
While booting tegra or hekate? Switch wont boot to OFW nor CFW

**Comment by Masamune3210** [comment]
While booting tegra

**Comment by BgomezSuperpapotas** [comment]
![WhatsApp Image 2021-12-12 at 1 01 07 PM](https://user-images.githubusercontent.com/92190797/145725792-c65cf420-90d2-426f-99c9-5a27951e3224.jpeg)
This is the error msg. Sorry for the offtopic, but there is any other way to unbrick/restore nand?

**Comment by BgomezSuperpapotas** [comment]
![WhatsApp Image 2021-12-12 at 1 03 13 PM](https://user-images.githubusercontent.com/92190797/145725849-46e28c63-ad7c-496e-bdda-1324b3767f27.jpeg)
After that it loads like this.

**Comment by suchmememanyskill** [comment]
Dump your keys via lockpick_rcm

**Comment by BgomezSuperpapotas** [comment]
done

**Comment by suchmememanyskill** [comment]
Well, now hold vol- while booting tegraexplorer and use it how you want? Closing this issue as TE boots. For unbricking support seek help in discord or somethint
