### ISSUE TITLE
use exFat instead of FAT32

### ISSUE THREAD

**Issue by Mouradif** [suchmememanyskill/TegraExplorer#6]
Hi

FAT32 cannot hold files that are heavier than 4GB, it's not ideal given how large some *.nsp files can be. Is it possible to have an option to format to exFat ?

**Comment by suchmememanyskill** [comment]
1. The exfat drivers inside the switch suck. This means that stuff will corrupt at some point when exfat is used. Fat32 is arguably the better option.
2. I do not condone the use of piracy. Dump your games yourself and they'll auto split.
