### ISSUE TITLE
File and directory timestamp

### ISSUE THREAD

**Issue by blueberryfigapricotrye** [suchmememanyskill/TegraExplorer#64]
TegraExplorer Version: v4.0.1

### Description
Hii,

it looks like TegraExplorer does not show timestamps for files and directories. If so, can you show how I can use this function?

If there is no support, then please support Modified and Created timestamps.

**Comment by suchmememanyskill** [comment]
TE does not show timestamps currently. I'm not interested in adding this. Sorry.

**Comment by blueberryfigapricotrye** [comment]
> TE does not show timestamps currently. I'm not interested in adding this. Sorry.

Is that a generally disinterest or just not interested in not adding it to the column for example? But as an alternative under the function "Properties", would be a possibility for you to add it in the future.

**Comment by suchmememanyskill** [comment]
General disinterest. I don't think it's that important to waste precious bytes on.

**Comment by blueberryfigapricotrye** [comment]
> General disinterest. I don't think it's that important to waste precious bytes on.

Displaying timestamps is a basic function of File Explorer. Why this disinterest? Is there a specific reason?

My Nintendo Switch has a very large SD card and the internal storage is also large, the hardware itself should have no problems supporting such a feature.

**Comment by suchmememanyskill** [comment]
1. I do not wish to deal with time or timezones.
2. You're correct, it does not. Fatfs should even have an interface to read the timestamp
3. Payloads have very limited space. TegraExplorer is super duper close to this limit.
