### ISSUE TITLE
Update for Firmware 14.1.1

### ISSUE THREAD

**Issue by YimosDoman** [suchmememanyskill/TegraExplorer#67]
Will you update soon?

**Comment by suchmememanyskill** [comment]
Does current TE not work on 14.1.1?

**Comment by YimosDoman** [comment]
Yes. It needs an update.

**Comment by YimosDoman** [comment]
The current one is two updates behind.

**Comment by YimosDoman** [comment]
Te 14.0.0 doesn't work out for tinfoil on my end.

**Comment by suchmememanyskill** [comment]
If you would've tried it, you would've noticed tegraexplorer works on the latest firmware. I don't need to update for every firmware version. Please refrain from opening issues before testing it

Ps: tinfoil is a nasty app (closed source, obfuscated) and you probably shouldn't use it for this reason
