### ISSUE TITLE
Extremely minor issue, single missing letter in FirmwareDump menu

### ISSUE THREAD

**Issue by ToxiClay** [suchmememanyskill/TegraExplorer#74]
After updating to `4.0.1-hotfix3` for HOS 15.0.0, I noticed a single missing letter while going into `FirmwareDump.te` to perform the dump. I don't know if this issue had been present in prior versions, but I certainly noticed it here.
![Screenshot_0ffb9e73](https://user-images.githubusercontent.com/13796683/198686159-c5c2222f-b0bd-4018-bd7a-efe11626aef1.jpg)

**Comment by suchmememanyskill** [comment]
i *think* this is proper grammer, and also [intended](https://github.com/suchmememanyskill/TegraExplorer/blob/master/scripts/FirmwareDump.te#L21) either way

**Comment by ToxiClay** [comment]
Wait, yeah, you're right, in a case like this. Apologies. It was simply very much noticed.
