### ISSUE TITLE
building Using MSYS

### ISSUE THREAD

**Issue by impeeza** [suchmememanyskill/TegraExplorer#75]
Hi I am setting up a MSYS environment to build Tegra Explorer, the steps I follow are:
- Install MSYS from latest release of https://github.com/msys2/msys2-installer/releases

Then Run:
`pacman -Syuu --noconfirm`
Until get "`there is nothing to do`" response
on `/etc/pacman.conf` add to end:
```
[dkp-libs]
Server = https://pkg.devkitpro.org/packages

[dkp-windows]
Server = https://pkg.devkitpro.org/packages/windows/$arch/
```
Then install the DevKitPro with the commands:

```
pacman-key --recv BC26F752D25B92CE272E0F44F7FD5492264BB9D0 --keyserver keyserver.ubuntu.com

pacman-key --lsign BC26F752D25B92CE272E0F44F7FD5492264BB9D0

pacman-key -l BC26F752D25B92CE272E0F44F7FD5492264BB9D0

pacman -U --noconfirm https://pkg.devkitpro.org/devkitpro-keyring.pkg.tar.xz

pacman -Syuu --noconfirm
```

After that Install the minimum packages:

`pacman -Sy --needed --noconfirm git make devkitARM mingw-w64-x86_64-gcc`

Clone the repository

`git clone --recursive https://github.com/suchmememanyskill/TegraExplorer.git`

And compile it:

```
cd TegraExplorer

export DEVKITPRO=/opt/devkitpro
export DEVKITARM=${DEVKITPRO}/devkitARM
export DEVKITPPC=${DEVKITPRO}/devkitPPC

export PATH=${DEVKITPRO}/tools/bin:$PATH

make
```

All works "fine" until the end but get the message:

```
make[1]: Leaving directory '/home/Impeeza/TegraExplorer/loader'
Payload size is 153061
Compressed Payload size is 1160
Max size is 126296 Bytes.
\e[1;33mPayload size exceeds limit!\e[0m
```

I am missing some step?

**Comment by suchmememanyskill** [comment]
Can you please point out the issue? I fail to see any

**Comment by impeeza** [comment]
Yes the official dkp install binaries for windows, I use the steps for use dkp on MSYS as stated on the page https://devkitpro.org/wiki/devkitPro_pacman under section "Customising Existing Pacman Install"

will try the DPK installer and see how it goes.

**Comment by impeeza** [comment]
just create a new Windows 11 install, install DevKitPro using https://github.com/devkitPro/installer/releases/latest and run the commands:


pacman -Syuu --noconfirm
pacman -Sy --needed --noconfirm git make devkitARM mingw-w64-x86_64-gcc
git clone --recursive https://github.com/suchmememanyskill/TegraExplorer.git
cd TegraExplorer
export PATH=/mingw64/bin/:$PATH
export DEVKITPRO=/opt/devkitpro
export DEVKITARM=${DEVKITPRO}/devkitARM
export DEVKITPPC=${DEVKITPRO}/devkitPPC
export PATH=${DEVKITPRO}/tools/bin:$PATH
make -j

and get the same error.

¿what environment do you use to build the payload?

thanks for your help.

**Comment by suchmememanyskill** [comment]
I haven't built TE in a while myself, but i used to use the dkp windows installer, selected the switch workload, and it just worked

Github actions also automatically builds it, but this uses dkp's docker containers

**Comment by impeeza** [comment]
I am really sucks at compiling he he he.

create a repo with a copy of the actual TegraExplorer one and get the same error:

![image](https://user-images.githubusercontent.com/41979604/200138006-d98c7956-3eac-4fd8-98b1-a9750c25a863.png)

Is not for me :P

**Comment by suchmememanyskill** [comment]
it looks like it compiled correctly though. The 'Payload size exceeds limit' can be ignored, as the compressed payload is below the max size

**Comment by impeeza** [comment]
Ok, thanks, will try the artifacts. regards.

**Comment by impeeza** [comment]
Yes It worked well,  create a virtual machine with Ubuntu and works fine too.  should be some quirky on MSYS in between the convertion of TegraExplorer.bin to TegraExplorer_small.bin for now closing the Issue, thanks a lot for your help.

**Comment by impeeza** [comment]
Problem found, you need to use MSYS NOT MinGW, my bad.

the packages needed are:

pacman -Sy --needed --noconfirm git make devkitARM gcc

all compiles fine.
