### ISSUE TITLE
is this supported on 15.0.1

### ISSUE THREAD

**Issue by Atomic646** [suchmememanyskill/TegraExplorer#77]
I know it was a minor update that didn't affect atmosphere, hekate nor sigpatches, but did it affect tegraexplorer?

**Comment by suchmememanyskill** [comment]
Well, does the keydump work on 15.0.1?

**Comment by suchmememanyskill** [comment]
Keydump works on 15.0.1

In the future, before opening such an issue, confirm first that it doesn't work, before opening an issue. In case it doesn't work, keydump simply won't work and you cannot access your internal storage

**Comment by SparkyDaPikachu** [comment]
key dumping works, but the "FirmwareDump.te" script does NOT work (at least for me) on 15.0.1
Hekate is on 5.9.0, and all i get is the following on screen before the switch becomes unresponsive (requires manual force-shutdown)
"Sys' fw is 15.0.1"

no other info is given, and must force-off the switch afterwards (time to RCM jig again)
I would provide logs, if i knew the log file's location.

**Comment by suchmememanyskill** [comment]
Please refrain from commenting unrelated information a closed issue.

This sounds like a duplicate of #58
