### ISSUE TITLE
An error occured from 16.0.0

### ISSUE THREAD

**Issue by EntropyDokiDoki** [suchmememanyskill/TegraExplorer#79]
It says 
Err: 21
Line" 202
File: source/main.c
Desc: Keydump failed

**Comment by suchmememanyskill** [comment]
Are you using the latest release?

**Comment by EntropyDokiDoki** [comment]
yes, running it on mariko

**Comment by suchmememanyskill** [comment]
TE on mariko does not support key dumping. Did you dump your keys via lockpick_rcm?

**Comment by EntropyDokiDoki** [comment]
lockpick_rcm is ok, thanks.
