### ISSUE TITLE
Cannot copy USER:save folder

### ISSUE THREAD

**Issue by rashevskyv** [suchmememanyskill/TegraExplorer#80]
Cannot copy `USER:save` folder. Tried on HOS 15.0.1 with TE 4.0.1-hotfix4. Process just freeze on first save-file with [0%]

**Comment by suchmememanyskill** [comment]
Is copying a folder broken entirely (even from and to sd)? Does copying a single file from USER:/save work?

**Comment by rashevskyv** [comment]
> Is copying a folder broken entirely (even from and to sd)?
No, sd to sd works fine. And copying savemeta folder from USER works fine too 

> Does copying a single file from USER:/save work?
No, it is freezing on 0%
Holding Vol+\- dose not interrupt process

I can easily copy single files from SYSTEM:/saves, btw
