### ISSUE TITLE
hotfix needed for HOS 16.0.3

### ISSUE THREAD

**Issue by urherenow** [suchmememanyskill/TegraExplorer#82]
Just blank-screens otherwise. No error message at all.

**Comment by suchmememanyskill** [comment]
I do not believe that firmware would be casuing that.

If firmware key extraction would fail, you would be unable to access internal storage, the rest of the payload would be accessible.

I need some more info:
- Define 'blank screen' (completely black? A white line on the top and bottom without any text?)
- What model of switch are you running this on

**Comment by gunt3001** [comment]
Also experiencing the same issue trying to work on my Swtich today. 

Chiming in a bit with my details:

- Blank screen after injecting RCM payload (tried several tools & machines, no difference)
- Original unpatched Switch model

Also, both Atmosphere and Hekate released hotfixes for 16.0.3 today; not sure if that's related.

**Comment by urherenow** [comment]
Mariko OLED. Launch payload from hekate. The screen just stays black. I just saw a previous hotfix for 16.0.0 and figured it needed the same sort of hotfix.

**Comment by suchmememanyskill** [comment]
That is very strange, there is no interaction with firmware before display init.....

I am currently not in possession of a switch, i can take a look later this week

**Comment by gunt3001** [comment]
Well as it turns out, I redownloaded the latest TE bin and it now works flawlessly. Must have been a corrupted download on my part. Sorry for the confusion!

**Comment by urherenow** [comment]
> > Mariko OLED. Launch payload from hekate. The screen just stays black. I just saw a previous hotfix for 16.0.0 and figured it needed the same sort of hotfix.
> 
> Fyi, TE does not support aula switches. A black screen is expected behaviour

Oh. Either I never noticed because I also have a release-day switch, or I used a fork. Dezem's fork works on OLED, by the way (in case you'd like to pull the required changes over).

**Comment by jangrewe** [comment]
I have a Mariko that ends up with:
```
Sys`   fw is 16.0.3
```
and then just hangs. I've retried this multiple times, and always let it sit for >10 minutes, but there's nothing else happening, and it does not respond to any joystick/buttons input.

**Comment by suchmememanyskill** [comment]
1. Please don't post on old issues
2. This is a duplicate of [this issue](https://github.com/suchmememanyskill/TegraExplorer/issues/58#issuecomment-984845331)
