### ISSUE TITLE
Seems to never load

### ISSUE THREAD

**Issue by Scynette** [suchmememanyskill/TegraExplorer#83]
OG Switch running on 16.0.3, whenever I inject payload, TegraRcmGUI just says (Not Responding) and doesn't seem to load.

I updated the switch firmware from an older version on the Switch itself before trying to reinstall the program, and I can't find any solutions online.

**Comment by suchmememanyskill** [comment]
Tegrarcmgui not responding is usually either an indication of a previously failed injection (force reboot the console) or you already being in a payload (reboot to rcm first). This is not an issue with the payload

**Comment by Scynette** [comment]
seems to be it, works now. Thank you
