### ISSUE TITLE
16.1 - [solved] - 

### ISSUE THREAD

**Issue by Leerz** [suchmememanyskill/TegraExplorer#87]
errors out upon loading on 16.1 and latest hekate and ams

**Comment by suchmememanyskill** [comment]
I have no idea what your issue is. Please make your issue more concise. 

If it helps you: please note down the steps to reproduce the issue and what you expected to happen vs what actually happened.

**Comment by lkuza2** [comment]
I just tried it on 16.1.0 and was able to successfully dump 16.1.0 and flash/update my emu partition from it

So I have no clue what they are talking about

**Comment by Leerz** [comment]
ahh forgive me, I copied the wrong version (4.4 instead of 4.5)
