### ISSUE TITLE
Reverse Script for compiling saves back from Guide?

### ISSUE THREAD

**Issue by LokeYourC3PH** [suchmememanyskill/TegraExplorer#88]
Hello there, I am looking for a script that can reverse what the "extract.py" achieves. That script unpacks the save files, and what I want is the opposite which repacks/recompiles the save files so that I can import them back into SysNAND/EmuNAND. Does anyone have that at hand? Guide I'm talking about (made by @suchmememanyskill : https://suchmememanyskill.github.io/guides/switchextractsaves/)
Thanks in advance 👍

**Comment by suchmememanyskill** [comment]
https://github.com/Thealexbarney/LibHac#usage

Also, why would you ever want to do this? Save managers exist for this reason

**Comment by LokeYourC3PH** [comment]
> https://github.com/Thealexbarney/LibHac#usage
> 
> Also, why would you ever want to do this? Save managers exist for this reason

Because I keep SysNAND clean from any tools at all, I only use Homebrew and such on EmuNAND, however I want to modify saves on SysNAND in a non-suspicious way, and for that I need to extract saves from SysNAND, modify them via EmuNAND or PC and then inject them back into SysNAND. This is a lot easier via using TegraExplorer than having to dump my entire SysNAND, extracting the save, injecting it back in and then restoring the SysNAND.

**Comment by suchmememanyskill** [comment]
I don't know what you want me to say here. This is a lot more error prone and risky (in terms of if you do it incorrectly, you could consider it a ban risk) than just using a save manager. I will not be supporting you in this endeavour

Anyway, good luck
