### ISSUE TITLE
EMUMMC failed to mount!

### ISSUE THREAD

**Issue by 1046329594** [suchmememanyskill/TegraExplorer#9]
I'm using this tool with file-based EmuMMC

**Comment by suchmememanyskill** [comment]
Attempted to fix in 405cb46. Please check if it works

Here's a [compiled copy](https://www.dropbox.com/s/efcfcktgp3xmfb4/TegraExplorer_405cb46.bin?dl=1)

**Comment by 1046329594** [comment]
It's working now.
