### ISSUE TITLE
Support for dumping 18.0.0?

### ISSUE THREAD

**Issue by OrGoN3** [suchmememanyskill/TegraExplorer#92]
Is this already working or does it need and update to the dumping script? Lockpick was already updated.

**Comment by suchmememanyskill** [comment]
Did you try to dump the firmware yet? What happens (does it work?)

The keydump is the only thing that TE needs to be updated for. It seems like the keydump works just fine

**Comment by OrGoN3** [comment]
I'll try right now. I thought key dump needed to be updated for the master key 11. I'll report back soon

**Comment by OrGoN3** [comment]
No errors. Verifying dump in daybreak. Validated! Sorry for the bother. I'm obviously not installing it just yet but it seems to dump 18 just fine.
